### ISSUE TITLE
notification error

### ISSUE THREAD

**Issue by karan-encanto** [axiftaj/Flutter-Firebase-Notifications#1]
why are you comment shownotification function, i have a som issue when app in running notification not popup.    D/FLTFireMsgReceiver(  935): broadcast received for message
I/flutter (  935): notifications title:karan
I/flutter (  935): notifications body:thakur
I/flutter (  935): notifications channel id:null
I/flutter (  935): notifications click action:null
I/flutter (  935): notifications color:null
I/flutter (  935): notifications count:null
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:425)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:326)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1146)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1462)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1299)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at android.os.Looper.loop(Looper.java:236)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/MethodChannel#dexterous.com/flutter/local_notifications(  935): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (  935): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/flutter (  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:425)
E/flutter (  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:326)
E/flutter (  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1146)
E/flutter (  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1462)
E/flutter (  935): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1299)
E/flutter (  935): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (  935): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (  935): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (  935): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (  935): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (  935): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (  935): 	at android.os.Looper.loop(Looper.java:236)
E/flutter (  935): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/flutter (  935): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (  935): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter (  935): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (  935): )
E/flutter (  935): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (  935): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (  935): <asynchronous suspension>
E/flutter (  935): #2      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:239:7)
E/flutter (  935): <asynchronous suspension>
E/flutter (  935):

**Comment by axiftaj** [comment]
> why are you comment shownotification function, i have a som issue when app in running notification not popup. D/FLTFireMsgReceiver( 935): broadcast received for message
> I/flutter ( 935): notifications title:karan
> I/flutter ( 935): notifications body:thakur
> I/flutter ( 935): notifications channel id:null
> I/flutter ( 935): notifications click action:null
> I/flutter ( 935): notifications color:null
> I/flutter ( 935): notifications count:null
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): Failed to handle method call
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:425)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:326)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1146)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1462)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1299)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at android.os.Handler.handleCallback(Handler.java:938)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at android.os.Handler.dispatchMessage(Handler.java:99)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at android.os.Looper.loop(Looper.java:236)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at android.app.ActivityThread.main(ActivityThread.java:8057)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 935): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
> E/flutter ( 935): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
> E/flutter ( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:425)
> E/flutter ( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:326)
> E/flutter ( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1146)
> E/flutter ( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1462)
> E/flutter ( 935): at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1299)
> E/flutter ( 935): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
> E/flutter ( 935): at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/flutter ( 935): at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> E/flutter ( 935): at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/flutter ( 935): at android.os.Handler.handleCallback(Handler.java:938)
> E/flutter ( 935): at android.os.Handler.dispatchMessage(Handler.java:99)
> E/flutter ( 935): at android.os.Looper.loop(Looper.java:236)
> E/flutter ( 935): at android.app.ActivityThread.main(ActivityThread.java:8057)
> E/flutter ( 935): at java.lang.reflect.Method.invoke(Native Method)
> E/flutter ( 935): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
> E/flutter ( 935): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
> E/flutter ( 935): )
> E/flutter ( 935): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
> E/flutter ( 935): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
> E/flutter ( 935): 
> E/flutter ( 935): #2 FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:239:7)
> E/flutter ( 935): 
> E/flutter ( 935):

I was playing with the source code, i have updated the code. 

Also do read the comment while sending notification from device carefully so you can send the correct data.
